const CENT_LIST = [
    [
        {cate_no:0, item_no:1, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:2, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:3, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:4, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:5, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:6, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:7, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:8, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:9, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:10, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:11, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:12, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:13, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:14, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:15, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:16, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:17, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:18, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:19, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:20, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:21, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:22, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:23, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:24, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:25, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:26, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:27, img_src:'page-img1.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:28, img_src:'page-img4.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:29, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
        {cate_no:0, item_no:30, img_src:'page-img10.jpg', sub_title:[''], sub_context1: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'], cent_doc: ['test1', 'tes2',] },
    ]
]

const CENT_TITLE = [
    [
        {cate_no:0, item_no:1, title:'간담췌센터 위ㆍ대장암'},
        {cate_no:0, item_no:2, title:'간센터'},
        {cate_no:0, item_no:3, title:'감염센터'},
        {cate_no:0, item_no:4, title:'대장항문센터'},
        {cate_no:0, item_no:5, title:'소아청소년 정신건강센터'},
        {cate_no:0, item_no:6, title:'소화기내신경센터'},
        {cate_no:0, item_no:7, title:'소화기암수술센터'},
        {cate_no:0, item_no:8, title:'신경센터'},
        {cate_no:0, item_no:9, title:'심뇌혈관센터'},
        {cate_no:0, item_no:10, title:'알레르기 센터'},
        {cate_no:0, item_no:11, title:'암재활프로그램'},
        {cate_no:0, item_no:12, title:'여성암센터'},
        {cate_no:0, item_no:13, title:'유방ㆍ갑상선암 센터'},
        {cate_no:0, item_no:14, title:'유방암센터'},
        {cate_no:0, item_no:15, title:'응급의료센터'},
        {cate_no:0, item_no:16, title:'인공신장센터'},
        {cate_no:0, item_no:17, title:'인터벤션센터(중재시술)'},
        {cate_no:0, item_no:18, title:'장례식장'},
        {cate_no:0, item_no:19, title:'재활치료센터'},
        {cate_no:0, item_no:20, title:'전립선ㆍ배뇨장애 센터'},
        {cate_no:0, item_no:21, title:'전립선암센터'},
        {cate_no:0, item_no:22, title:'척추관절센터'},
        {cate_no:0, item_no:23, title:'초음파진단센터'},
        {cate_no:0, item_no:24, title:'췌장담도센터'},
        {cate_no:0, item_no:25, title:'턱얼굴수술센터(양악센터)'},
        {cate_no:0, item_no:26, title:'페암수술센터'},
        {cate_no:0, item_no:27, title:'항암방사선치료센터'},
        {cate_no:0, item_no:28, title:'호스피스완화의료병동'},
        {cate_no:0, item_no:29, title:'호흡기센터'},
    ]
]
const HOSPI_TITLE = [
    [
        {cate_no:0, item_no:1, title:'간센터'},
        {cate_no:0, item_no:5, title:'소화기암수술센터'},
        {cate_no:0, item_no:10, title:'여성암센터'},
        {cate_no:0, item_no:11, title:'유방ㆍ갑상선암 센터'},
        {cate_no:0, item_no:15, title:'인터벤션센터(중재시술)'},
        {cate_no:0, item_no:18, title:'전립선암센터'},
        {cate_no:0, item_no:24, title:'페암수술센터'},
        {cate_no:0, item_no:25, title:'항암방사선치료센터'},
    ]
]
const LIST_N = [
    [
        {cate_no:0, item_no:1, name:'1'},
        {cate_no:0, item_no:1, name:'1'},
        {cate_no:0, item_no:2, name:'1'},
        {cate_no:0, item_no:3, name:'1'},
        {cate_no:0, item_no:4, name:'5'},
        {cate_no:0, item_no:5, name:'5'},
        {cate_no:0, item_no:6, name:'5'},
        {cate_no:0, item_no:7, name:'5'},
        {cate_no:0, item_no:8, name:'5'},
        {cate_no:0, item_no:9, name:'5'},
        {cate_no:0, item_no:10, name:'10'},
        {cate_no:0, item_no:11, name:'10'},
        {cate_no:0, item_no:12, name:'10'},
        {cate_no:0, item_no:13, name:'10'},
        {cate_no:0, item_no:14, name:'10'},
        {cate_no:0, item_no:15, name:'10'},
        {cate_no:0, item_no:16, name:'10'},
        {cate_no:0, item_no:17, name:'10'},
        {cate_no:0, item_no:18, name:'10'},
        {cate_no:0, item_no:19, name:'5'},
        {cate_no:0, item_no:20, name:'5'},
        {cate_no:0, item_no:21, name:'5'},
        {cate_no:0, item_no:22, name:'5'},
        {cate_no:0, item_no:23, name:'1'},
        {cate_no:0, item_no:24, name:'1'},
        {cate_no:0, item_no:25, name:'1'},
        {cate_no:0, item_no:26, name:'1'},
        {cate_no:0, item_no:27, name:'1'},
        {cate_no:0, item_no:28, name:'1'},
    ]
]