const DOCTOR = [
    [
        // 0번 묵음 : 가정의학과
        {cate_no:0, item_no:1, img_src:'fam_medi1', name:'고귀한 과장', medi_con:'가정의학과', medi_his_con:'한국의학연구소 내시경센터 진료과장', one_speci_con:'종합검진/ 위·대장 내시경/ 건강상담', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['진료','','진료','','진료',''], morn_color:['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger',], afte_color: ['cir_primary','','cir_primary','','cir_primary','']},
        {cate_no:0, item_no:2, img_src:'fam_medi2', name:'강동완 과장', medi_con:'가정의학과 검진센터', medi_his_con:'동아대학교병원 가정의학과 외래교수', one_speci_con:'종합검진 / 위대장내시경 / 비만클리닉(대시증후근) / 건강상담', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['진료','진료','진료','진료','',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:0, item_no:3, img_src:'fam_medi3', name:'이현웅 과장', medi_con:'가정의학과 검진센터', medi_his_con:'아주대학교병원 진료조교수', one_speci_con:'일차의료 / 초음파 / 내시경', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['','진료','진료','','진료',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger'], afte_color: ['','cir_primary','cir_primary','','cir_primary','']}
    ],
    [
        // 1번 묵음 : 가정의학과 검진센터 (온종합병원 검진센터)
        {cate_no:1, item_no:1, img_src:'fam_medi_alpha1', name:'김동현 과장', medi_con:'간센터', medi_his_con:'', one_speci_con:'상복부초음파 / 시술초음파 / 간섬유화 및 지방간 스캔검사 / 간암 / 간경변 / 알코올성 간질환 / 지방간질환', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','문의',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_success','']},
        {cate_no:1, item_no:2, img_src:'fam_medi1', name:'고귀한 과장', medi_con:'가정의학과', medi_his_con:'한국의학연구소 내시경센터 진료과장', one_speci_con:'종합검진/ 위·대장 내시경/ 건강상담', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['진료','','진료','','진료',''], morn_color:['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger',], afte_color: ['cir_primary','','cir_primary','','cir_primary','']},
        {cate_no:1, item_no:3, img_src:'fam_medi2', name:'강동완 과장', medi_con:'가정의학과 검진센터', medi_his_con:'동아대학교병원 가정의학과 외래교수', one_speci_con:'종합검진 / 위대장내시경 / 비만클리닉(대시증후근) / 건강상담', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['진료','진료','진료','진료','',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:1, item_no:4, img_src:'fam_medi3', name:'이현웅 과장', medi_con:'가정의학과 검진센터', medi_his_con:'아주대학교병원 진료조교수', one_speci_con:'일차의료 / 초음파 / 내시경', morn_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','수술/검사','수술/검사'], afte_schedule:['','진료','진료','','진료',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_danger','cir_danger','cir_danger'], afte_color: ['','cir_primary','cir_primary','','cir_primary','']}
    ],
    [
        // 2번 묵음 : 간담췌외과 (외과 사람들도 몇몇 포함 되어있음)
        {cate_no:2, item_no:1, img_src:'surgrey1', name:'문기명 교수', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간담췌 및 이식·혈관 외과 전임의', one_speci_con:'간담췌 외과 / 혈관 이식 외과 / 중환자 및 외상 외과 / 유방 및 갑상선 외과', morn_schedule:['진료','진료','진료','진료','수술/검사','문의'], afte_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_danger','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:2, item_no:2, img_src:'surgrey2', name:'박광민 의무원장', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간·담·췌외과 주임교수', one_speci_con:'간담도췌장암수술 / 담낭질환 / 복강경수술(단일통로 복강경 담낭절제술) / 간이식', ifram_src: 'https://www.youtube.com/embed/FxGwggzensQ', morn_schedule:['수술/검사','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','수술/검사','진료','수술/검사',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','']},
        {cate_no:2, item_no:3, img_src:'hep_pan1', name:'이상엽 과장', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간·담·췌외과 전문의', one_speci_con:'간담도췌외과 / 복강격수술 / 담도결석 치료 ERCP(내시경적 역행성 취담도관조영술) / 담도 결석 치료 복강경 담관 결석 제거', morn_schedule:['진료','수술/검사','진료','수술/검사','진료','문의'], afte_schedule:['수술/검사','수술/검사','','수술/검사','진료',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_primary','cir_success'], afte_color: ['cir_danger','cir_danger','','cir_danger','cir_primary','']},
        {cate_no:2, item_no:4, img_src:'hep_pan2', name:'박요한 교수', medi_con:'간담췌외과', medi_his_con:'서울아산병원 전임의', one_speci_con:'감암, 담도암, 담낭암, 췌장암, 담석증, 담낭용종, 복강경, 담낭수술, 간이식', morn_schedule:['수술/검사','수술/검사','수술/검사','진료','수술/검사','문의'], afte_schedule:['진료','진료','진료','','수술/검사',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_primary','cir_danger','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_danger','']}
    ],
    [
        // 3번 묵음 : 내과
        {cate_no:3, item_no:1, img_src:'cardiology_department', name:'이현국 내과부장', medi_con:'심장내과', medi_his_con:'부산대학교 의학전문대학원 내과학 겸임교수', one_speci_con:'협심증, 급성심근경색(관상동맥중재술), 고혈압, 고지혈증, 심부전, 판막질환 (심초음파), 부정맥, 동서맥 및 동정지 (심박동기시술)', ifram_src: 'https://www.youtube.com/embed/3nIsp2JoLMc', morn_schedule:['수술/검사','진료','진료','수술/검사','진료','문의'], afte_schedule:['진료','','수술/검사','진료','',''], note: '▶ 토요일 : 외래문의(051-607-0247)', morn_color:['cir_danger','cir_primary','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_primary','','cir_danger','cir_primary','','']},
        {cate_no:3, item_no:2, img_src:'internal_medicine_dapartment1', name:'한상영 센터장', medi_con:'간센터', medi_his_con:'동아대학교병원 간센터 소장', one_speci_con:'간암, 경간동맥화학요법, 고주파열치료', morn_schedule:['진료','진료','진료','진료','진료',''], afte_schedule:['진료','잔료','','진료','',''], morn_color:['cir_primary','cir_primary','진료','cir_primary','cir_primary','',], afte_color: ['cir_primary','cir_primary','','cir_primary','','']},
        {cate_no:3, item_no:3, img_src:'department_of_gastroenterology1', name:'김연우 과장', medi_con:'소화기 내과', medi_his_con:'동아대학교병원 소화기내과 임상교수', one_speci_con:'위대장내시경 / 치료내시경 / 용종절제술 위대장질환 / 간질환 / 췌담도질환', morn_schedule:['진료','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','','진료','수술/검사','진료',''], note: '▶ 토요일 : 2, 4주 진료', morn_color:['cir_primary','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','','cir_primary','cir_danger','cir_primary','']},
        {cate_no:3, item_no:4, img_src:'department_of_gastroenterology2', name:'박철우 과장', medi_con:'소화기 내과', medi_his_con:'동의의료원 내과 전문의', one_speci_con:'위대장내시경 / 치료내시경 / 용종절제술 식도질환 / 위 지환 / 대장질환 간췌장담도질환', morn_schedule:['수술/검사','수술/검사','진료','수술/검사','','문의'], afte_schedule:['진료','진료','','진료','수술/검사',''], morn_color: ['cir_danger','cir_danger','cir_primary','cir_danger','','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_danger','']},
        {cate_no:3, item_no:5, img_src:'department_of_gastroenterology3', name:'은명 과장', medi_con:'소화기 내과', medi_his_con:'미국 하버드 메디칼 연수', one_speci_con:'위대장내시경/치료내시경/용종절제술/위대장암진단/역류성식도염/소화성궤양/과민성대장증후군/췌장담도질환/췌장담도암진단/간질환', ifram_src: 'https://www.youtube.com/embed/qE40EoPjz3c',  morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
        {cate_no:3, item_no:6, img_src:'respiratory_medicine', name:'유 흥 VIP검진센터장', medi_con:'호흡기내과', medi_his_con:'고신대병원 내과전문의', one_speci_con:'만성질환(고혈압, 당뇨, 고지혈증), 감염병, 위내시경, 상복부초음파, 경동맥초음파, 골다공증, B,C형간염, 갑상선질환', ifram_src: 'https://www.youtube.com/embed/TwL--bpEov4', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:3, item_no:7, img_src:'department_of_renal_medicine1', name:'곽임수 교수', medi_con:'신장내과', medi_his_con:'부산대학교 의과대학 교수', one_speci_con:'혈액투석 / 신장질환 / 고혈압 / 당뇨병', ifram_src: 'https://www.youtube.com/embed/GNatfOtZugo',  morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','',''], note: '▶ 토요일: 2,4주 진료 / 온라인예약 불가, ☎ 전화문의 부탁드립니다.', morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:3, item_no:8, img_src:'department_of_renal_medicine2', name:'전하경 과장', medi_con:'신장내과', medi_his_con:'부산대학교병원 신장내과 전임의', one_speci_con:'사구체신염(혈뇨, 단백뇨), 급성 및 만성 신부전, 당뇨병성 신질환, 고혈압, 혈액투석', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], note: '▶ 토요일 : 1, 3주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
        {cate_no:3, item_no:9, img_src:'endocri_depart', name:'김미경 과장', medi_con:'내분비 내과', medi_his_con:'부산대학교 의과대학 내과학 외래교수', one_speci_con:'당뇨병 / 겁상선질환 / 골다공증 / 고지혈증 / 부신질환 / 뇌하수체질환', morn_schedule:['진료','진료','문의','진료','진료','문의'], afte_schedule:['진료','잔료','','진료','','문의'], morn_color:['cir_primary','cir_primary','cir_success','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','','cir_success']},
        {cate_no:3, item_no:10, img_src:'hematology_oncology', name:'권혁찬 교수', medi_con:'혈액종양내과', medi_his_con:'동아대학교 의과대학 부교수', one_speci_con:'고형종양 (유방암, 위암, 대장암, 폐암, 각종 고형암), 혈액종양', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], note: '▶ 토요일 : 격주 진료', morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
        {cate_no:3, item_no:11, img_src:'fam_medi_alpha1', name:'김동현 과장', medi_con:'간센터', medi_his_con:'', one_speci_con:'상복부초음파 / 시술초음파 / 간섬유화 및 지방간 스캔검사 / 간암 / 간경변 / 알코올성 간질환 / 지방간질환', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','문의',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_success','']},
    ],
    [
        // 4번 묵음 : 내분비 내과
        {cate_no:4, item_no:1, img_src:'endocri_depart', name:'김미경 과장', medi_con:'내분비 내과', medi_his_con:'부산대학교 의과대학 내과학 외래교수', one_speci_con:'당뇨병 / 겁상선질환 / 골다공증 / 고지혈증 / 부신질환 / 뇌하수체질환', morn_schedule:['진료','진료','문의','진료','진료','문의'], afte_schedule:['진료','잔료','','진료','','문의'], morn_color:['cir_primary','cir_primary','cir_success','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','','cir_success']},
    ],
    [
        // 5번 묵음 : 마취통증의학과
        {cate_no:5, item_no:1, img_src:'anesthetic_pain1', name:'김관식 수술실장', medi_con:'마취통증의학과', medi_his_con:'경북대학교 마취통증의학과 전문의', one_speci_con:'마취 클리닉 일반마취 / 소아마취 / 노인마취 / 장기이식마취', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:5, item_no:2, img_src:'anesthetic_pain2', name:'유기찬 과장', medi_con:'마취통증의학과', medi_his_con:'부산대학교 의과전문대학원 졸업', one_speci_con:'TPI 교육이수 신경통증 클리닉 / 마취 클리닉 심폐마취 / 소아마취 / 노인마취 / 장기이식 마취', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:5, item_no:3, img_src:'anesthetic_pain3', name:'홍수영 과장', medi_con:'마취통증의학과', medi_his_con:'부산대학교 의과전문대학원 졸업', one_speci_con:'신경통 클리닉 / 마취 클리닉 심폐마취 / 소아마취 / 노인마취 / 장기이식 마취', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']}
    ],
    [
        // 6번 묵음 : 방사선종양학과
        {cate_no:6, item_no:1, img_src:'raditation_tumor1', name:'류성열 암센터장', medi_con:'방사선종양학과', medi_his_con:'한국원자력의학원 방사선종양학과 부장', one_speci_con:'방사선종양학 / 핵의학 / PET-CT', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
        {cate_no:6, item_no:2, img_src:'raditation_tumor2', name:'강위생 박사', medi_con:'방사선종양학과', medi_his_con:'서울대학교 물리학 이학박사', one_speci_con:'방사선종양학', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','','',], afte_color: ['','','','','','']},
    ],
    [
        // 7번 묵음 : 비뇨의학과
        {cate_no:7, item_no:1, img_src:'urology', name:'김재식 교수', medi_con:'비뇨의힉과', medi_his_con:'가톨릭의대 인천성모병원 비뇨기과부교수', one_speci_con:'비교기 암(전립선 암, 방광암, 신장암) 수술 및 최소침습치료 혈뇨 / 음낭수종 / 요로감염(신우신염, 방광염, 전립선염, 부고환염) 전립선비대증 (내시경수술) / 전립선염 / 요로결석 (내시경수술, 충격파쇄석술) 여성 배뇨장애 (요실금, 과민성방광) / 발기부전 / 불임 / 소아 야노증 신경인성 방광 (척수 및 뇌손상, 치매, 뇌출혈 및 뇌졸중, 당뇨)', ifram_src: 'https://www.youtube.com/embed/KW9I4W7xKlU',  morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','수술/검사','진료','수술/검사','',''], note: '▶ 토요일 : 2, 4주 진료' , morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_danger','cir_primary','cir_danger','','']},
    ],
    [
        // 8번 묵음 : 산부인과
        {cate_no:8, item_no:1, img_src:'obstetrics_gynecology1', name:'김 철 박사', medi_con:'산부인과', medi_his_con:'부산 춘해병원 산부인과 과장 / 의무원장', one_speci_con:'부인암(자궁경부암, 자궁내막암, 난소암), 일반 부인과 질환, 자궁근종, 자궁선근증, 양성난소종양, 복강경수술, 자궁경수술', ifram_src: 'https://www.youtube.com/embed/ANliqfAOiCI', morn_schedule:['진료','수술/검사','진료','수술/검사','수술/검사','문의'], afte_schedule:['진료','진료','','진료','진료',''], note: '▶ 토 - 2, 4주 진료', morn_color:['cir_primary','cir_danger','cir_primary','cir_danger','cir_danger','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
        {cate_no:8, item_no:2, img_src:'obstetrics_gynecology2', name:'김지연 과장', medi_con:'산부인과', medi_his_con:'부산대학교 의학과 의학박사', one_speci_con:'부인과 내시경수술(단일공, 자궁경수술) / 부인종양 요실금 및 배뇨장애 / 골반염증질환 산전질환 / 월경장애 / 폐경기관리 골반이완 교정수술 / 여성 외음부 성형 및 재건수술', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], note: '▶ 토요일 : 1, 3주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
    ],
    [
        // 9번 묵음 : 성형센터
        {cate_no:9, item_no:1, img_src:'plastic_surgery', name:'김석권 원장', medi_con:'성형센터', medi_his_con:'동아대학교 의과대학 성형외과 주임교수', one_speci_con:'안면 윤곽 성형 / 유방 성형 / 코·눈커풀 안면 주름성형 / 구순구개열 / 모발이식 무질증 재건 / 소이증 수술 . 트렌스젠드 수술', morn_schedule:['진료','수술/검사','진료','수술/검사','진료','문의'], afte_schedule:['진료','수술/검사','진료','','수술/검사',''], morn_color:['cir_primary','cir_danger','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_primary','cir_danger','cir_primary','','cir_danger','']},
        {cate_no:9, item_no:2, img_src:'fam_medi2', name:'한봉주 원장', medi_con:'성형센터', medi_his_con:'인제대 의과대학 성형외과 외래교수', one_speci_con:'눈·코 지방이식수술 / 욕창치료', morn_schedule:['수술/검사','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','문의','진료','진료',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','cir_primary','cir_success','cir_primary','cir_primary','']},
    ],
    [
        // 10번 묵음 : 소아청소년과
        {cate_no:10, item_no:1, img_src:'children_adolescents1', name:'오무영 센터장', medi_con:'소아 청소년과', medi_his_con:'인제대 부산백병원 소아청소년과 교수', one_speci_con:'소아호흡기 / 알레르기 (천식, 알레르기 비염, 두드러기 , 아토피 피부염) / 면역질환 / 결핵 . 감염질환 / 피부질환', morn_schedule:['진료','','진료','','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], note: '▶ 토요일 : 1, 3주 진료', morn_color:['cir_primary','','cir_primary','','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:10, item_no:2, img_src:'children_adolescents2', name:'송정윤 과장', medi_con:'소아 청소년과', medi_his_con:'계명대학교 동산의료원 소아청소년과 전고으이', one_speci_con:'신생아 및 영유아 클리닉 (신생아 질환 및 예방접종, 육아상담, 영유아발달) 소아 호흡기 / 소아 소화기 및 영양상담 / 소아 알레르기 및 피부질환', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], note: '▶ 토요일 : 2, 4주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
    ],
    [
        // 11번 묵음 : 소화기내과
        {cate_no:11, item_no:1, img_src:'department_of_gastroenterology1', name:'김연우 과장', medi_con:'소화기 내과', medi_his_con:'동아대학교병원 소화기내과 임상교수', one_speci_con:'위대장내시경 / 치료내시경 / 용종절제술 위대장질환 / 간질환 / 췌담도질환', morn_schedule:['진료','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','','진료','수술/검사','진료',''], note: '▶ 토요일 : 2, 4주 진료', morn_color:['cir_primary','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','','cir_primary','cir_danger','cir_primary','']},
        {cate_no:11, item_no:2, img_src:'department_of_gastroenterology2', name:'박철우 과장', medi_con:'소화기 내과', medi_his_con:'동의의료원 내과 전문의', one_speci_con:'위대장내시경 / 치료내시경 / 용종절제술 식도질환 / 위 지환 / 대장질환 간췌장담도질환', morn_schedule:['수술/검사','수술/검사','진료','수술/검사','','문의'], afte_schedule:['진료','진료','','진료','수술/검사',''], morn_color: ['cir_danger','cir_danger','cir_primary','cir_danger','','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_danger','']},
        {cate_no:11, item_no:3, img_src:'department_of_gastroenterology3', name:'은명 과장', medi_con:'소화기 내과', medi_his_con:'미국 하버드 메디칼 연수', one_speci_con:'위대장내시경/치료내시경/용종절제술/위대장암진단/역류성식도염/소화성궤양/과민성대장증후군/췌장담도질환/췌장담도암진단/간질환', ifram_src: 'https://www.youtube.com/embed/qE40EoPjz3c',  morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']}
    ],
    [
        // 12번 묵음 : 신경과
        {cate_no:12, item_no:1, img_src:'department_of_neurology1', name:'노순기 부원장', medi_con:'신경과', medi_his_con:'미국존스홉킨스병원 간질센터 postdoc Epilepsy Fellow 수료', one_speci_con:'어지럼증, 두통, 치매, 파킨슨, 손발저림, 뇌졸증 및 뇌질환, 뇌파, 간질', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','','진료','','진료',''], note: '▶ 토요일 : 2, 4주 진료', morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','','cir_primary','','cir_primary','']},
        {cate_no:12, item_no:2, img_src:'department_of_neurology2', name:'하상욱 과장', medi_con:'신경과', medi_his_con:'고신대학교 복음병원 신경과 전문의', one_speci_con:'뇌졸중 등 뇌혈관 질환 어지럼증 / 두통 / 치매 / 간질 / 손발 저림 등 말초신경 질환 근육질환', ifram_src: 'https://www.youtube.com/embed/yUtjCyD5cn4', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], note: '▶ 토요일 : 1, 3, 5주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
    ],
    [
        // 13번 묵음 : 신경외과
        {cate_no:13, item_no:1, img_src:'neurosurgery1', name:'이명기 교수', medi_con:'신경외과', medi_his_con:'가톨릭의과대학 신경외과 외래교수', one_speci_con:'뇌신경(뇌졸중·떨림·사경·파킨슨병·삼차신경통·디스토니아) 신경통증 / 보톡스 주사 / 정위수술 / 방사선수술', ifram_src: 'https://www.youtube.com/embed/kXHpoLgOODQ', morn_schedule:['진료','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['진료','진료','수술/검사','진료','수술/검사',''], morn_color:['cir_primary','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_primary','cir_primary','cir_danger','cir_primary','cir_danger','']},
        {cate_no:13, item_no:2, img_src:'neurosurgery2', name:'최재영 센터장', medi_con:'신경외과', medi_his_con:'고신대학교 복음병원 신경외과 조교수', one_speci_con:'뇌혈관 중재적 치료(동맥류, 뇌동정맥 기형) 뇌졸중(뇌출혈, 뇌경색) 소아신경 외과(모야모야병) 두부외상 척추질환', morn_schedule:['진료','수술/검사','진료','진료','진료','문의'], afte_schedule:['수술/검사','진료','수술/검사','수술/검사','진료',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_danger','cir_primary','cir_danger','cir_danger','cir_primary','']},
        {cate_no:13, item_no:3, img_src:'neurosurgery3', name:'김종열 척추센터장', medi_con:'신경외과', medi_his_con:'연세대학교 강남세브란스병원 척추센터 교수', one_speci_con:'최소 침습 척추수술 퇴행성 척추 질환(디스크 탈출증, 척추관 협착증) 척추 변형,외상,종양,감염', ifram_src: 'https://www.youtube.com/embed/GKFyCnAXi70', morn_schedule:['진료','수술/검사','진료','수술/검사','진료','문의'], afte_schedule:['진료','수술/검사','진료','수술/검사','수술/검사',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_primary','cir_success'], afte_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_danger','']},
        {cate_no:13, item_no:4, img_src:'neurosurgery4', name:'조성민 과장', medi_con:'신경외과', medi_his_con:'고신대 복음병원 전임의', one_speci_con:'신경외과 척추질환(디스크, 협착증, 골절, 감염)/두부외상', morn_schedule:['수술/검사','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','수술/검사','진료','진료',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','cir_success'], afte_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_primary','']}
    ],
    [
        // 14번 묵음 : 신장내과
        {cate_no:14, item_no:1, img_src:'department_of_renal_medicine1', name:'곽임수 교수', medi_con:'신장내과', medi_his_con:'부산대학교 의과대학 교수', one_speci_con:'혈액투석 / 신장질환 / 고혈압 / 당뇨병', ifram_src: 'https://www.youtube.com/embed/GNatfOtZugo',  morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','',''], note: '▶ 토요일: 2,4주 진료 / 온라인예약 불가, ☎ 전화문의 부탁드립니다.', morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:14, item_no:2, img_src:'department_of_renal_medicine2', name:'전하경 과장', medi_con:'신장내과', medi_his_con:'부산대학교병원 신장내과 전임의', one_speci_con:'사구체신염(혈뇨, 단백뇨), 급성 및 만성 신부전, 당뇨병성 신질환, 고혈압, 혈액투석', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], note: '▶ 토요일 : 1, 3주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
    ],
    [
        // 15번 묵음 : 심장내과
        {cate_no:15, item_no:1, img_src:'cardiology_department', name:'이현국 내과부장', medi_con:'심장내과', medi_his_con:'부산대학교 의학전문대학원 내과학 겸임교수', one_speci_con:'협심증, 급성심근경색(관상동맥중재술), 고혈압, 고지혈증, 심부전, 판막질환 (심초음파), 부정맥, 동서맥 및 동정지 (심박동기시술)', ifram_src: 'https://www.youtube.com/embed/3nIsp2JoLMc', morn_schedule:['수술/검사','진료','진료','수술/검사','진료','문의'], afte_schedule:['진료','','수술/검사','진료','',''], note: '▶ 토요일 : 외래문의(051-607-0247)', morn_color:['cir_danger','cir_primary','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_primary','','cir_danger','cir_primary','','']},
    ],
    [
        // 16번 묵음 : 안과
        {cate_no:16, item_no:1, img_src:'ophthalmology', name:'장영준 과장', medi_con:'안과', medi_his_con:'마산김안과병원 녹내장 전문 진료과장 역임', one_speci_con:'백내장, 녹내장, 라식', morn_schedule:['','','','','',''], afte_schedule:['','진료','','','',''], morn_color:['','','','','','',], afte_color: ['','cir_primary','','','','']},
    ],
    [
        // 17번 묵음 : 이비인후과
        {cate_no:17, item_no:1, img_src:'otolaryngology1', name:'이일우 과장', medi_con:'이비인후과', medi_his_con:'부산대학교 이비인후과 전임의사', one_speci_con:'비염, 부비동염, 비골골절, 중이염, 외이도염, 어지러움, 난청, 이명, 편도, 아데노이드, 후두질환', ifram_src: 'https://www.youtube.com/embed/auagcELsIng', morn_schedule:['진료','진료','진료','수술/검사','진료','문의'], afte_schedule:['진료','수술/검사','진료','진료','',''], note: '▶ 토요일 : 1, 3주 진료', morn_color:['cir_primary','cir_primary','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_primary','cir_danger','cir_primary','cir_primary','','']},
        {cate_no:17, item_no:2, img_src:'otolaryngology2', name:'이봉희 과장', medi_con:'이비인후과', medi_his_con:'인제대학교 부산백병원 이비인후과 의학박사', one_speci_con:'코골이 및 수면무호흡증, 코:알레르기 비염 및 부비동염/귀:어지러움, 이명, 난청, 중이염/목:편도염, 인후두 질환', ifram_src: 'https://www.youtube.com/embed/eYEW2NAgcfI', morn_schedule:['진료','수술/검사','수술/검사','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], morn_color: ['cir_primary','cir_danger','cir_danger','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
    ],
    [
        // 18번 묵음 : 영상의학과
        {cate_no:18, item_no:1, img_src:'department_of_imaging1', name:'최종철 과장', medi_con:'간센터', medi_his_con:'동아대학교 의과대학 영상의학과 교수', one_speci_con:'', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:18, item_no:2, img_src:'department_of_imaging2', name:'최기복 소장', medi_con:'영상의학과', medi_his_con:'해운대백병원 부교수(인터벤션 분야)', one_speci_con:'인터컨벤션 영상의학', ifram_src: 'https://www.youtube.com/embed/iFIAHT7xbWI', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:18, item_no:3, img_src:'department_of_imaging3', name:'문태용 교수', medi_con:'영상의학과', medi_his_con:'부산대학병원 영상의학과 교수', one_speci_con:'', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','',''], afte_color: ['','','','','','']},
        {cate_no:18, item_no:4, img_src:'department_of_imaging4', name:'최정현 과장', medi_con:'영상의학과', medi_his_con:'', one_speci_con:'', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
        {cate_no:18, item_no:5, img_src:'department_of_imaging5', name:'김은미 과장', medi_con:'영상의학과', medi_his_con:'', one_speci_con:'MRI / CT / 초음파 / X-ray 복부영상의학, 복부초음파유도중재적시술, 간암, 고주파열치료', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary'], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']}
    ],
    [
        // 19번 묵음 : 외과
        {cate_no:19, item_no:1, img_src:'', name:'문기명 교수', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간담췌 및 이식·혈관 외과 전임의', one_speci_con:'간담췌 외과 / 혈관 이식 외과 / 중환자 및 외상 외과 / 유방 및 갑상선 외과', morn_schedule:['진료','진료','진료','진료','수술/검사','문의'], afte_schedule:['수술/검사','수술/검사','수술/검사','수술/검사','',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_danger','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
        {cate_no:19, item_no:2, img_src:'', name:'박광민 의무원장', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간·담·췌외과 주임교수', one_speci_con:'간담도췌장암수술 / 담낭질환 / 복강경수술(단일통로 복강경 담낭절제술) / 간이식', ifram_src: 'https://www.youtube.com/embed/FxGwggzensQ', morn_schedule:['수술/검사','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','수술/검사','진료','수술/검사',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','']},
        {cate_no:19, item_no:3, img_src:'surgical1', name:'고상화 과장', medi_con:'외과', medi_his_con:'부산대학교병원 외과 조교수', one_speci_con:'대장암 / 직장암 / 치핵 / 치루 / 항문질환 / 복강경수술', ifram_src: 'https://www.youtube.com/embed/CYCalfW_7mE', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
        {cate_no:19, item_no:4, img_src:'', name:'박요한 교수', medi_con:'간담췌외과', medi_his_con:'서울아산병원 전임의', one_speci_con:'감암, 담도암, 담낭암, 췌장암, 담석증, 담낭용종, 복강경, 담낭수술, 간이식', morn_schedule:['수술/검사','수술/검사','수술/검사','진료','수술/검사','문의'], afte_schedule:['진료','진료','진료','','수술/검사',''], morn_color: ['cir_danger','cir_danger','cir_danger','cir_primary','cir_danger','cir_success'], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_danger','']},
        {cate_no:19, item_no:5, img_src:'', name:'이상엽 과장', medi_con:'간담췌외과', medi_his_con:'서울아산병원 간·담·췌외과 전문의', one_speci_con:'간담도췌외과 / 복강격수술 / 담도결석 치료 ERCP(내시경적 역행성 취담도관조영술) / 담도 결석 치료 복강경 담관 결석 제거', morn_schedule:['진료','수술/검사','진료','수술/검사','진료','문의'], afte_schedule:['수술/검사','수술/검사','','수술/검사','진료',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_primary','cir_success'], afte_color: ['cir_danger','cir_danger','','cir_danger','cir_primary','']},
        {cate_no:19, item_no:6, img_src:'surgical2', name:'김동헌 병원장', medi_con:'외과', medi_his_con:'제22대 부산대학교병원장 / 제14대 부산광역시 의료원장 / 제12대 부산보훈병원장', one_speci_con:'외과종양학 / 위장관외과 / 위암 / 위양성종양', morn_schedule:['','','','','',''], afte_schedule:['','','','진료','',''], morn_color: ['','','','','',''], afte_color: ['','','','cir_primary','','']},
        {cate_no:19, item_no:7, img_src:'surgical3', name:'최필조 센터장', medi_con:'흉부외과', medi_his_con:'동아대학교 의과대학 흉부외과 주임교수', one_speci_con:'폐암수술/폐, 흉부종양의 흉강 내시경 수술/다한증 수술 및 비수술적 치료/기흉/하지 정맥류 누두흉(오목가슴) 등의 흉벽기형', morn_schedule:['진료','수술/검사','진료','수술/검사','수술/검사','문의'], afte_schedule:['진료','수술/검사','','수술/검사','진료',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_danger','cir_success'], afte_color: ['cir_primary','cir_danger','','cir_danger','cir_primary','']},
        {cate_no:19, item_no:8, img_src:'surgical4', name:'주재우 과장', medi_con:'외과', medi_his_con:'부산삼육병원 외과 과장', one_speci_con:'위암 / 대장암 / 복강경 내시경 수술 / 화상', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']}
    ],
    [
        // 20번 묵음 : 응급의학과
        {cate_no:20, item_no:1, img_src:'emergency1', name:'신우성 센터장', medi_con:'응급의학과', medi_his_con:'인제대학교 부산백병원 응급의학과 전문의', one_speci_con:'소생, 재난, 외상, 중독 / 응급처치, 중환자 / 응급질환 전반', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color:['','','','','','',], afte_color: ['','','','','','']},
        {cate_no:20, item_no:2, img_src:'emergency2', name:'전창원 과장', medi_con:'응급의학과(외과)', medi_his_con:'경상대학교 의과대학 졸업', one_speci_con:'지역응급의료기관(24시간 응급진료 및 수술 가능)', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','','',], afte_color: ['','','','','','']},
        {cate_no:20, item_no:3, img_src:'emergency3', name:'정민웅 과장', medi_con:'응급의학과(내과)', medi_his_con:'인제대학교 의과대학 졸업', one_speci_con:'응급의학', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','',''], afte_color: ['','','','','','']},
        {cate_no:20, item_no:4, img_src:'emergency4', name:'이강호 과장', medi_con:'외과', medi_his_con:'서울 아산병원 외과 전문의', one_speci_con:'일차의료 / 초음파 / 내시경', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','',''], afte_color: ['','','','','','']},
        {cate_no:20, item_no:5, img_src:'emergency5', name:'하대명 과장', medi_con:'응급의학과', medi_his_con:'창원국립경상대학교병원 응급의료센터 진료교수', one_speci_con:'일차의료 / 초음파 / 내시경', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','',''], afte_color: ['','','','','','']},
        {cate_no:20, item_no:6, img_src:'emergency6', name:'박영민 과장', medi_con:'응급의학과', medi_his_con:'부산대학교병원 응급의학과', one_speci_con:'일차의료 / 초음파 / 내시경', morn_schedule:['','','','','',''], afte_schedule:['','','','','',''], morn_color: ['','','','','',''], afte_color: ['','','','','','']}
    ],
    [
        // 21번 묵음 : 정신건강의학과
        {cate_no:21, item_no:1, img_src:'mental_health1', name:'김상엽 소장', medi_con:'정신건강의학과', medi_his_con:'삼성서울병원 소아청소년 정신과 임상교수', one_speci_con:'학습능력장애 / 발달장애 / 정서장애 / 뚜렛장애 주의력결핍과잉행동장애 (ADHD) / 스트레스 청소년클리닉 / 가정상담클리닉', ifram_src: 'https://www.youtube.com/embed/IQkuPqWsIUo', morn_schedule:['진료','진료','','','진료','문의'], afte_schedule:['진료','진료','진료','','진료',''], note: '▶ 토요일 : 2, 4주 진료', morn_color:['cir_primary','cir_primary','','','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','','cir_primary','']},
        {cate_no:21, item_no:2, img_src:'mental_health2', name:'이수진 과장', medi_con:'정신건강의학과', medi_his_con:'메리놀병원 정신건강의학과 진료과장', one_speci_con:'노인기 정서장애 / 공황장애 / 기분장애 / 수면 장애 우울증 /조울증 / 불안증 / 정신증 스트레스 소아기 정서 행동발달문제 / 청소년기 우울증 / 소아청소년 정신질환', ifram_src: 'https://www.youtube.com/embed/HYng79HGTxw', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','',''], note: '▶ 토요일 : 1, 3주 진료', morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','','']},
    ],
    [
        // 22번 묵음 : 정형외과
        {cate_no:22, item_no:1, img_src:'orthopedics1', name:'구인회 부원장', medi_con:'정형외과', medi_his_con:'수지접합 부산경남 최다수술, 열(10)손가락 절단환자 재접합 성공, "베스트닥터 in 부산" 선정(부산일보)', one_speci_con:'수지접합 수술, 미세현미경 수술, 소아질환 수술, 사지외상 / 재건', ifram_src: 'https://www.youtube.com/embed/XZo0Oqmep4Q', morn_schedule:['진료','진료','진료','수술/검사','진료','문의'], afte_schedule:['수술/검사','수술/검사','','진료','수술/검사',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_danger','cir_danger','','cir_primary','cir_danger','']},
        {cate_no:22, item_no:2, img_src:'orthopedics2', name:'김윤준 진료부원장', medi_con:'정형외과', medi_his_con:'인제대학교 부산백병원 정형외과 전임교수 및 건국대학교병원 외래부교수', one_speci_con:'슬관절 / 견관절 / 고관절 / 족관절 스포츠 손상 / 골절 관절내시경 전문', ifram_src: 'https://www.youtube.com/embed/ZH6o76qnQUA', morn_schedule:['진료','수술/검사','진료','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','수술/검사','','진료',''], morn_color: ['cir_primary','cir_danger','cir_primary','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','cir_primary','cir_danger','','cir_primary','']},
        {cate_no:22, item_no:3, img_src:'orthopedics3', name:'김동준 과장', medi_con:'정형외과', medi_his_con:'영국 라이팅병원 정형외과센터 연수', one_speci_con:'어깨·팔꿈치·관절 통증 클리닉 스포츠 손상 내시경 수술', morn_schedule:['수술/검사','진료','수술/검사','진료','진료','문의'], afte_schedule:['진료','','수술/검사','수술/검사','',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_primary','cir_success'], afte_color: ['cir_primary','','cir_primary','cir_danger','cir_danger','']}
    ],
    [
        // 23번 묵음 : 진단검사의학과
        {cate_no:23, item_no:1, img_src:'diagnostic_examination', name:'손종애 과장', medi_con:'진단검사의학과', medi_his_con:'인제대학교 부산백병원 진단검사의학과 전공의 수련', one_speci_con:'임상미생물학, 진단혈액학, 진단면역학, 임상화학, 수혈의학', morn_schedule:['문의','문의','문의','문의','문의','문의'], afte_schedule:['문의','문의','문의','문의','문의',''], morn_color:['cir_success','cir_success','cir_success','cir_success','cir_success','cir_success',], afte_color: ['cir_success','cir_success','cir_success','cir_success','cir_success','']},
    ],
    [
        // 24번 묵음 : 취담담도내과
        {cate_no:24, item_no:1, img_src:'chwidamdo_internal_medicine', name:'박은택 센터장', medi_con:'췌장담도내과', medi_his_con:'고신대 복음병원 췌장담도내과 교수', one_speci_con:'췌장·담도계질환 / -췌장계:급-만성췌장염, 췌장암, 췌장낭종 / -담도계:담석증, 담낭염, 담관염, 담관암', ifram_src: 'https://www.youtube.com/embed/sTjsy4YbNrk', morn_schedule:['수술/검사','수술/검사','진료','수술/검사','진료','문의'], afte_schedule:['진료','수술/검사','수술/검사','수술/검사','',''], morn_color:['cir_danger','cir_danger','cir_primary','cir_danger','cir_primary','cir_success',], afte_color: ['cir_primary','cir_dagner','cir_dagner','cir_dagner','','']},
    ],
    [
        // 25번 묵음 : 치과
        {cate_no:25, item_no:1, img_src:'dental_clinic1', name:'김종렬 원장', medi_con:'치과', medi_his_con:'부산대 치의대 구강악안면외과학교실 교수', one_speci_con:'양악수술 / 주걱텅 / 비대칭 / 돌출입 사각턱 / 광대축소 / 안면윤곽술 구순구개열', morn_schedule:['수술/검사','진료','수술/검사','수술/검사','진료',''], afte_schedule:['수술/검사','진료','수술/검사','수술/검사','수술/검사',''], morn_color:['cir_danger','cir_primary','cir_danger','cir_danger','cir_primary','',], afte_color: ['cir_danger','cir_primary','cir_danger','cir_danger','cir_danger','']},
        {cate_no:25, item_no:2, img_src:'dental_clinic2', name:'이의정 과장', medi_con:'치과', medi_his_con:'부산대학교 치과대학 치의학전문대학원 졸업', one_speci_con:'근관치료 및 수복치료 / 일반 보철치료 / 사랑니 발치 / 치주치료', ifram_src: 'https://www.youtube.com/embed/msOZ-7lgPmc', morn_schedule:['진료','진료','진료','진료','진료','진료'], afte_schedule:['진료','','진료','진료','진료',''], morn_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_primary',], afte_color: ['cir_primary','','cir_primary','cir_primary','cir_primary','']},
        {cate_no:25, item_no:3, img_src:'dental_clinic3', name:'서정석 과장', medi_con:'치과', medi_his_con:'부산대학교병원 구강악안면외과 전문의', one_speci_con:'임플란트 / 사랑니 발치 /보존치료 / 보철치료 / 치주치료', morn_schedule:['수술/검사','진료','수술/검사','수술/검사','진료','진료'], afte_schedule:['수술/검사','진료','수술/검사','수술/검사','수술/검사',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_danger','cir_primary','cir_primary'], afte_color: ['cir_danger','cir_primary','cir_danger','cir_danger','cir_danger','']}
    ],
    [
        // 26번 묵음 : 혈액종양내과
        {cate_no:26, item_no:1, img_src:'hematology_oncology', name:'권혁찬 교수', medi_con:'혈액종양내과', medi_his_con:'동아대학교 의과대학 부교수', one_speci_con:'고형종양 (유방암, 위암, 대장암, 폐암, 각종 고형암), 혈액종양', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','','진료','진료',''], note: '▶ 토요일 : 격주 진료', morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','','cir_primary','cir_primary','']},
    ],
    [
        // 27번 묵음 : 호흡기 내과
        {cate_no:27, item_no:1, img_src:'respiratory_medicine', name:'유 흥 VIP검진센터장', medi_con:'호흡기내과', medi_his_con:'고신대병원 내과전문의', one_speci_con:'만성질환(고혈압, 당뇨, 고지혈증), 감염병, 위내시경, 상복부초음파, 경동맥초음파, 골다공증, B,C형간염, 갑상선질환', ifram_src: 'https://www.youtube.com/embed/TwL--bpEov4', morn_schedule:['진료','진료','진료','진료','진료','문의'], afte_schedule:['진료','진료','진료','진료','진료',''], morn_color:['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','cir_success',], afte_color: ['cir_primary','cir_primary','cir_primary','cir_primary','cir_primary','']},
    ],
    [
        // 28번 묵음 : 흉부외과
        {cate_no:28, item_no:1, img_src:'cardiothoracic_surgery', name:'최필조 센터장', medi_con:'흉부외과', medi_his_con:'동아대학교 의과대학 흉부외과 주임교수', one_speci_con:'폐암수술/폐, 흉부종양의 흉강 내시경 수술/다한증 수술 및 비수술적 치료/기흉/하지 정맥류 누두흉(오목가슴) 등의 흉벽기형', morn_schedule:['진료','수술/검사','진료','수술/검사','수술/검사','문의'], afte_schedule:['진료','수술/검사','','수술/검사','진료',''], note: '▶ 토요일 : 전화문의 부탁드립니다.', morn_color: ['cir_primary','cir_danger','cir_primary','cir_danger','cir_danger','cir_success'], afte_color: ['cir_primary','cir_danger','','cir_danger','cir_primary','']},
    ],
    [
        // 29번 묵음 : 의료진소개 (욕창클리닉)
        {cate_no:29, item_no:1, img_src:'fam_medi2', name:'한봉주 원장', medi_con:'성형센터', medi_his_con:'인제대 의과대학 성형외과 외래교수', one_speci_con:'눈·코 지방이식수술 / 욕창치료', morn_schedule:['수술/검사','진료','수술/검사','진료','수술/검사','문의'], afte_schedule:['수술/검사','진료','문의','진료','진료',''], morn_color: ['cir_danger','cir_primary','cir_danger','cir_primary','cir_danger','cir_success',], afte_color: ['cir_danger','cir_primary','cir_success','cir_primary','cir_primary','']},
    ],

]

const DOC_TITLE = [
    // 0번 묵음 : 전체중에 의사 소개 폐이지가 따로 있는 것들만 
    // (주석처리 된것들은 폐이지가 따로 있는 센터들 또는 겹치는 것들을 하나의 과로 묶거나 사이트가 없거나 (화상클리닉 없음))
    [
        {cate_no:0, item_no:1, title: '가정의학과', content: '수진자 개인 및 그 가족들의 건강을 지속적, 포괄적, 개별적으로 돌보아주기 위한 전문과입니다. 즉, 수진자가 아플 때나 건강할 때나 건강을 책임지는 의료를 제공하는 것을 의미합니다. 이를 위해 가정의학과에서는 급, 만성 질환의 진단 및 치료, 향후 관리뿐만 아니라 건강한 사람들에게는 건강의 증진 및 유지, 질병 예방을 위한 건강 상담 및 관리를 제공합니다.' },
        {cate_no:0, item_no:2, title: '온종합병원 검진센터', content: '' },
        {cate_no:0, item_no:3, title: '간담췌외과', content: '간, 담도 및 췌장에 생기는 양성 질환(간내결석, 담낭결석 등등) 및 악성 질환에 대한 수술적 치료 및 보존적 치료를 담당하는 분야입니다. 간담췌암에 대한 치료로 지역 선도의 다학제적 접근에 의한 치료를 시행하고 있으며 복강경 간절제 및 췌담도 수술을 시행하고 있습니다. 또한 말기 간질환환자에 대한 간이식수술을 시행하고 있습니다.' },
        // {cate_no:0, item_no:101, title: '간센터', content: '' },
        // {cate_no:0, item_no:102, title: '관절·척추 센터', content: '' },
        // {cate_no:0, item_no:103, title: '기억력개선 치매 클리닉', content: '뇌와 척수(중추신경), 말초신경 및 근육에 발생하는 질환을 진단하고 치료하며 치매클리닉, 간질 클리닉, 뇌졸중 클리닉, 말초신경 및 근육질환 클리닉 등 전문 클리닉과 신경심리검사실, 뇌파검사실, 근전도검사실 등 특수검사실을 운영하여 보다 전문적인 진료와 치료에 최선을 다하고 있습니다.' },
        {cate_no:0, item_no:4, title: '내과', content: '주로 감염증 ·순환기질환 ·신경계질환 ·소화기계질환 ·혈액질환 ·호흡기질환 ·내분비선질환 ·비뇨기질환 ·알레르기성질환 ·신진대사질환 ·중독 등을 진료하며, 온종합병원 내과는 일반내과, 내분비내과, 소화기내과, 신장내과, 심장내과, 혈액종양내과 . 호흡기내과 등 각 영역별 진료를 시행합니다.' },
        {cate_no:0, item_no:5, title: '내분비 내과', content: '당뇨병, 갑상선질환, 고지혈증, 골다공증 및 골대사질환, 비만, 뇌하수체 및 부신 질환,성장장애 등 우리 몸의 내분비기관 및 이들이 만들어내는 주요호르몬과 관련된 각종 대사질환 및 내분비기관의 양성종양 등의 조기발견 및 진단과 치료를 위해 최고의 내분비대사내과 전문의에 의한 전문진료서비스를 실시하고 있습니다.' },
        // {cate_no:0, item_no:104, title: '두통클리닉', content: '' },
        {cate_no:0, item_no:6, title: '마취통증의학과', content: '환자를 먼저 생각하는 세심하고 안전한 마취를 통해 수술환자 마취와 중환자 관리, 응급처치, 호흡관리, 통증관리 등을 전문적으로 하고 있습니다.' },
        {cate_no:0, item_no:7, title: '방사선종양학과', content: '방사선을 이용하여 암을 치료하는 임상의학의 한 분야로서 수술, 항암화학요법과 함께 종양치료에서 핵심적인 역할을 하는 방사선치료를 담당하고 있습니다.' },
        {cate_no:0, item_no:8, title: '비뇨의학과', content: '남성의 비뇨기관 및 생식기질환, 성기능장애 및 불임, 여성과 소아의 비뇨기계에 대한 진료, 요로결석에 대한 체외충격파쇄석술을 시행하고 있습니다. 비뇨의학과는 비뇨기 종양, 신장이식, 남성의학(성기능 장애, 남성불임), 소아비뇨기학, 여성비뇨기학, 배뇨장애, 내비뇨기학 등을 다룹니다.' },
        // {cate_no:0, item_no:105, title: '비만클리닉', content: '' },
        {cate_no:0, item_no:9, title: '산부인과', content: '모든 여성의 건강을 지켜드리기 위해 임신에 관련된 질환 및 여성의 생식기관에서 발생하는 모든 질환을 전문적으로 진료하고 있습니다. 뿐만 아니라 여성의 질성형 (소음순·이쁜이수술), 비만 / 쁘띠성형 (보톡스 ·필러·녹는실) 등 풍부한 시술경험과 노하우를 가진 산부인과 전문의와 여성의 마음을 배려한 여성 전문의의 편안한 진료로 각종 부인과적 질환에 대한 예방, 진단 및 치료를 시행합니다.' },
        {cate_no:0, item_no:10, title: '성형센터', content: '구조적 변형 또는 기형의 수정과 기능적 결함의 교정을 주로 하는 외과의 특수분야로 신체 외부에 나타나는 선천성 기형 또는 후천성 변형이나 결손을 그 기능과 모양에 있어서 정상에 근사하게 교정해 주며 미용성형수술과 재건성형수술 등을 담당합니다.' },
        {cate_no:0, item_no:11, title: '소아청소년과', content: '신생아부터 사춘기에 이르기까지 소아의 전반적인 질환을 진단하고 치료하며 단순히 질병을 치료하는 이외에 소아의 성장, 발달에 대한 평가 및 육아상담 등을 통해서 아이가 건강하게 자랄수 있도록 도와줍니다.' },
        {cate_no:0, item_no:12, title: '소화기내과', content: '대학병원 교수 출신 전문 의료진으로 풍부한 임상경험과 진료로 보다 수준높은 의료서비스를 제공하고 있으며, 식도, 위, 소장, 대장 질환과 간 질환, 췌장 및 담도(담낭) 질환 등 각종 소화기 질환에 대해 전문적인 진료 및 치료를 담당합니다.' },
        // {cate_no:0, item_no:106, title: '소화기 암수술센터', content: '' },
        // {cate_no:0, item_no:107, title: '소화기내과 내신경센터', content: '' },
        {cate_no:0, item_no:13, title: '신경과', content: '뇌와 척수(중추신경), 말초신경 및 근육에 발생하는 질환을 진단하고 치료하며 치매클리닉, 간질 클리닉, 뇌졸중 클리닉, 말초신경 및 근육질환 클리닉 등 전문 클리닉과 신경심리검사실, 뇌파검사실, 근전도검사실 등 특수검사실을 운영하여 보다 전문적인 진료와 치료에 최선을 다하고 있습니다.' },
        {cate_no:0, item_no:14, title: '신경외과', content: '뇌, 척추, 척수, 말초신경등 신경 계통에 관계된 질환이나 외상 등을 진단하고 치료하며, 다수의 신경계 손상환자의 치료 및 뇌졸중, 뇌출혈 등 응급수술과 뇌수술을 전문적으로 시행합니다. 아울러 신경통증, 척추 신경, 사경의 전문진료와 파킨슨병수술, 뇌혈관 질환에 대한 뇌혈관 내 시술 등 일반 병원에서 치료가 힘든 고난도 수술이 요구되는 환자 치료에 전혀 어려움이 없게 항상 준비하고 있습니다.' },
        {cate_no:0, item_no:15, title: '신장내과', content: '각종 신장질환을 다루고 있는 분야로 사구체질환(혈뇨 및 단백뇨), 신증후군, 요로감염증, 요로결석증, 낭성신질환, 유전성 신질환, 급성 신부전, 만성 신부전 등 신장질환들과 당뇨병성 신증, 고혈압성 신증, 전신성홍반성낭창, 각종 혈관염, 교원성 질환, 전해질 및 산-염기 평형 장애 등 합병증의 전문 치료를 시행합니다. 온 종합병원 인공신장실은 병원 13층(승강기 6·7호기 이용)에 위치하고 있으며, 혈액투석실과 복막투석실로 운영하고 있습니다. 혈액투석실은 전문의가 상주하여 즉각적인 처치와 진료 및 상담을 하고 있으며, 전문 간호사가 혈액투석을 시행하고 있습니다.' },
        // {cate_no:0, item_no:108, title: '심·뇌혈관 센터', content: '' },
        {cate_no:0, item_no:16, title: '심장내과', content: '심장 및 혈관질환에 대한 질병을 진단하고 치료하는 내과로 관상동맥질환(협심증, 심근경색, 급사 등), 고혈압, 판막질환, 부정맥 등의 질병을 진료하고 있으며 양질의 전문적인 진료, 환자 중심의 진료, 신속하고 효과적인 진료가 체계적으로 전달되도록 노력하고 있습니다.' },
        {cate_no:0, item_no:17, title: '안과', content: '협력병원인 정말 근사한 정근안과병원과 연계하여 안과질환의 적극적인 치료를 제공하고 있습니다. 최신 최첨단 장비와 전문의료진으로 구성된 정말 근사한 정근안과에서는 각종 안과질환에 대한 검사 및 진단에 필요한 장비를 갖추고 전문적인 진료로 최선의 의료서비스를 제공하고 있습니다. 특히, 꿈의 시력교정술인 5초 라식(옵티에피라식)을 비롯해 , 눈물관 수술(눈물흘림), 백내장(초음파,레이저) 수술, 색맹클리닉(이노말로스코프), 안성형(쌍꺼풀, 안검내반)수술클리닉, 콘텍트렌즈 클리닉 등 안질환의 전문적인 치료를 시행합니다.' },
        {cate_no:0, item_no:18, title: '이비인후과', content: '이비인후과는 크게 귀 질환과 코 질환, 두경부 질환을 다루며 외이도염, 중이염, 내이염 등과 같은 다양한 염증성 질환에서부터 이명, 난청, 어지럼, 안면신경마비나 종양성 질환, 축농증(부비동염), 알레르기성 비염, 비중격만곡증, 코골이 및 수면무호흡 등을 다룹니다.' },
        // {cate_no:0, item_no:109, title: '여성암센터', content: '' },
        {cate_no:0, item_no:19, title: '영상의학과', content: '영상의학과는 방사선 및 자기, 초음파를 이용하여 진단과 치료를 담당하며 본원의 영상의학과는 새로운 의료영상기기를 이용한 다양한 진단과정과 중재적 시술을 통해, 환자의 진단과 치료에 중대한 역할을 수행하고 있습니다. 본원에서는 특수촬영(위장관조영, 경정맥 신우조영술, 배뇨성요도 방광조영술, 자궁난관조영술, 유방촬영, 관절조영, 혈관촬영 등), 초음파촬영, 전신전산화 단층촬영(CT), 자기공명영상 촬영(MRI), 치과용 X-선 촬영, 골다공증 검사 등과 최신 진단 장비를 가동하고 있습니다.' },
        {cate_no:0, item_no:20, title: '외과', content: '주로 수술로 기형 ·외상 ·염증 ·종양(腫瘍) 등을 진료하며, 상부위장관, 간담도계, 대장항문학, 갑상선 및 기타두경부외과, 유방외과, 소아외과 등 각 영역별 진료를 시행합니다. 온 종합병원 외과는 최신 의료 장비를 갖추고 가장 안전하고 확실한 외과 질환의 치료를 시행하고 있습니다.' },
        // {cate_no:0, item_no:110, title: '유방암·갑상선암센터', content: '' },
        {cate_no:0, item_no:21, title: '응급의학과', content: '응급의학과는 즉각적인 의학적 주의가 필요한 급성 질환이나 손상의 치료를 시행하고 있습니다. 온 종합병원 응급의학과는 지역응급의료기관으로서 보건복지부 평가 1등을 차지한 바 있으며 지역에서 응급환자 발생시 무엇보다 신속하고 전문적인 처치와 치료를 시행하고 있습니다.' },
        // {cate_no:0, item_no:111, title: '인공 신장센터', content: '' },
        // {cate_no:0, item_no:112, title: '인지발달 증진센터', content: '' },
        // {cate_no:0, item_no:113, title: '재활 치료센터', content: '' },
        // {cate_no:0, item_no:114, title: '전립선 암셈터', content: '' },
        {cate_no:0, item_no:22, title: '정신건강의학과', content: '정신건강 전문클리닉을 운영하여 스트레스, 불안장애, 우울증을 비롯하여 정신장애, 수면장애, 노인성 정신질환, 정신분열증 등의 주요 정신병 및 기질적 정신 장애를 포함해 소아청소년정신건강의학과를 전문으로 화병센터 등 특화된 진료를 시행하고 있습니다.' },
        {cate_no:0, item_no:23, title: '정형외과', content: '몸을 움직일 때 필요한 골격, 관절, 근육, 건, 인대, 척추, 척수 및 말초신경 등의 운동기관의 질환과 외상을 치료합니다. 슬관절 및 견관절 전치환수술, 광범위한 척추수술, 고관절, 족부외과적수술, 수부수술, 미세수술, 악성 골종양, 관절경을 이용한 진단 및 수술 등의 분야에 전문적인 연구와 치료가 시행되도록 힘쓰고 있습니다.' },
        {cate_no:0, item_no:24, title: '진단검사의학과', content: '진단검사의학과에서는 인체에서 유래하는 각종 혈액, 소변, 체액 등의 검체를 이용하여 적절한 검사를 시행함으로써 질병의 진단, 예후 판단과 치료에 관계되는 검사들을 시행하고 해석하는 검사의학 분야의 업무를 취급합니다. 또한 인체의 감염병을 진단하기 위하여, 세균, 바이러스, 진균 등 각종 미생물을 증균하여 동정합니다. 혈액은행에서는 병원 내 수형일 필요한 모든 곳에 혈액을 공흡하는 일을 맡고 있으며, 최근에는 각종 유전검사를 시행하여 질병과 관련된 새로운 유전 정보를 제공하고 있습니다.' },
        {cate_no:0, item_no:25, title: '췌장담도내과', content: '' },
        {cate_no:0, item_no:26, title: '치과', content: '치과, 구강악안면외과는 각종 치과질환에 대한 검사 및 진단에 필요한 장비를 갖추고 치아와 잇몸 및 턱, 얼굴에 관련된 다양한 질병에 대해 전문적인 진료와 최선의 의료서비스를 제공하고 있습니다. 치아수복 및 일반보철치료, 심미보철치료, 치주치료(풍치치료), 악교정 수술, 턱-얼굴수술, 안면골절의 수술, 임플란트(치아매식술)등을 통해 저작기능과 아름다움을 회복하도록 도와드립니다.' },
        // {cate_no:0, item_no:115, title: '턱얼굴수술 센터', content: '' },
        // {cate_no:0, item_no:116, title: '폐암 수술센터', content: '' },
        {cate_no:0, item_no:27, title: '혈액종양내과', content: '급성 및 만성 백혈병, 악성 림프종, 골수이형성증후군, 다발성 골수종, 재생불량성 빈혈 및 기타 일반혈액질환 (백혈구, 혈소판, 빈혈 관련)에 대하여 전문 의료진의 진료가 이루어지고 있습니다. 종양내과에서 하는 가장 중요한 일은 환자들의 항암 약물치료를 전문으로 합니다. 종양내과에서 진료중인 종양 질환으로는 보건복지부에서 중점관리하고 있는 6개암(위암, 대장암, 간암, 유방암, 폐암, 자궁경부암)과 두경부암, 구강암, 골육종 및 각종 육종, 각종 전이암, 췌담도암, 비뇨기암, 부인암 및 피부암 등이 있습니다.' },
        {cate_no:0, item_no:28, title: '호흡기 내과', content: '숨을 쉬는 기관지와 폐 및 그 장기에 생길 수 있는 여러 질환인 감기, 폐암, 결핵, 기도질환(천식, 만성 폐쇄성 폐질환), 간질성 폐질환(폐섬유화증, 호산구성 폐렴), 폐렴, 폐색전증 등을 다룹니다. 온 종합병원 호흡기내과는 각종 호흡기 질환의 예방, 환자교육, 진단 및 치료를 담당하고 있습니다.' },
        // {cate_no:0, item_no:117, title: '화상클리닉', content: '' },
         // {cate_no:0, item_no:118, title: '항암방사선치료센터', content: '' },
        {cate_no:0, item_no:29, title: '흉부외과', content: '인체 중 흉부, 즉 가슴에 위치하는 심장, 폐, 기관, 식도, 대동맥 등 생명 유지에 기본이 되는 중요 장기의 질환과 흉벽, 종격동, 횡격막, 늑막 등에서 발생된 질환을 진단하고 치료하는 전문 진료 분과로 다양한 혈관 질환에 대한 진료도 담당하고 있으며 양질의 전문적인 진료, 환자 중심의 진료, 신속하고 효과적인 진료가 체계적으로 전달되도록 노력하고 있습니다.' },
        {cate_no:0, item_no:30, title: '의료진소개', content: '' }
    ]
]